mqtt:
  enabled: true
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: admin
  password: password
  stats_interval: 60
  qos: 0
cameras:
  N01:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:qwerty12345@192.168.101.10:554/stream1
          roles:
            - detect
            - record
  S01:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.200.10:554/1
          roles:
            - detect
            - record
  S02:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:qwerty12345@192.168.101.11:554/stream1
          roles:
            - detect
            - record
objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - bus
    - dog
    - cat
detect:
  enabled: true
  width: 1280
  height: 720
  fps: 5
  min_initialized: 2
  max_disappeared: 25
  stationary:
    interval: 50
    threshold: 50
record:
  enabled: true
  retain:
    days: 7
    mode: all
review:
  alerts:
    enabled: true
    labels:
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - dog
      - cat
  detections:
    enabled: true
    labels:
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - dog
      - cat
motion:
  enabled: true
  threshold: 30
  lightning_threshold: 0.8
  improve_contrast: true
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  retain:
    default: 10
  quality: 100
semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: true
classification:
  bird:
    enabled: false
version: 0.16-0
